import { DefaultTheme, DarkTheme } from '@react-navigation/native';

export const palette = {
  cream: '#FFF7EC',
  warmWhite: '#FFFCF7',
  oatmeal: '#F8E7D2',
  parchment: '#F1DCC0',
  cocoa: '#2B2B2B',
  umber: '#6B6259',
  olive: '#2A9D8F',
  moss: '#1D746A',
  sage: '#CBE9E4',
  forest: '#153B35',
  petrol: '#1D5F57',
  deepNavy: '#12302C',
  softBlue: '#8FD6CC',
  sky: '#E4F6F3',
  coral: '#E76F51',
  coralDark: '#C9573F',
  terracotta: '#F4A261',
  butter: '#FFD89F',
  lilac: '#FFE8DD',
  blush: '#FFD4C9',
  mint: '#A7DDD4',
  white: '#FFFFFF',
  danger: '#C94735',
  success: '#2A9D8F',
  warning: '#E19A3D',
};

export const themes = {
  light: {
    mode: 'light' as const,
    colors: {
      ...palette,
      background: palette.cream,
      backgroundAlt: '#F8F2E9',
      surface: palette.white,
      surfaceElevated: palette.white,
      surfaceWarm: '#FFF0E4',
      surfaceCool: '#E1F4F1',
      surfaceCalm: '#F8F2E9',
      surfaceBotanical: '#E1F4F1',
      surfaceLilac: '#FDE9E5',
      surfacePressed: '#F1E9DE',
      glass: 'rgba(255, 252, 247, 0.9)',
      text: palette.cocoa,
      textMuted: '#5F5750',
      textSoft: '#8A817A',
      inverseText: palette.cream,
      border: '#E6DCCD',
      primary: '#F4A261',
      primarySoft: '#FFF0E4',
      secondary: '#2A9D8F',
      secondarySoft: '#E1F4F1',
      tertiary: '#58BDB1',
      tertiarySoft: palette.sky,
      accent: palette.coral,
      accentSoft: '#FDE9E5',
      calm: '#2A9D8F',
      calmSoft: '#E1F4F1',
      botanical: palette.moss,
      illustratedLine: '#2B2B2B',
      tab: palette.white,
      overlay: 'rgba(43, 43, 43, 0.54)',
    },
  },
  dark: {
    mode: 'dark' as const,
    colors: {
      ...palette,
      background: '#0F1716',
      backgroundAlt: '#1C2B28',
      surface: '#162220',
      surfaceElevated: '#1C2B28',
      surfaceWarm: '#3A2A1A',
      surfaceCool: '#17312E',
      surfaceCalm: '#1C2B28',
      surfaceBotanical: '#243633',
      surfaceLilac: '#3A201B',
      surfacePressed: '#243633',
      glass: 'rgba(22, 34, 32, 0.92)',
      text: '#F7F3EE',
      textMuted: '#D8D0C7',
      textSoft: '#AAA297',
      inverseText: '#10211E',
      border: '#2E423F',
      primary: '#F4A261',
      primarySoft: '#3A2A1A',
      secondary: '#2A9D8F',
      secondarySoft: '#17312E',
      tertiary: '#73D8CC',
      tertiarySoft: '#214C45',
      accent: '#F07D60',
      accentSoft: '#4D302A',
      calm: '#55C6B9',
      calmSoft: '#244E47',
      botanical: '#8FE0D6',
      illustratedLine: '#FFEFE1',
      tab: '#162220',
      overlay: 'rgba(17, 24, 22, 0.64)',
    },
  },
};

export type AppTheme = (typeof themes)[keyof typeof themes];

export const makeNavigationTheme = (theme: AppTheme) => ({
  ...(theme.mode === 'dark' ? DarkTheme : DefaultTheme),
  colors: {
    ...(theme.mode === 'dark' ? DarkTheme.colors : DefaultTheme.colors),
    primary: theme.colors.primary,
    background: theme.colors.background,
    card: theme.colors.surface,
    text: theme.colors.text,
    border: theme.colors.border,
    notification: theme.colors.accent,
  },
});

export const urgencyColors = {
  baixa: palette.success,
  media: palette.warning,
  alta: palette.coral,
  emergencia: palette.danger,
};
